### PR TITLE
Polish translation of the application

### PR DESCRIPTION
**Pull request by kplich**
A few remarks before the translation could be used in production:

- I'm not entirely sure in what context translations by name `channel_name`, `channel_description`, `reminder_title` and `notifs` will be used and therefore also not entirely sure about the correctness of my translation
- should I mention 'parsing' explicitly while translating `error_parsing`, or could I simply write about reading a file?
- Polish verbs and adjectives take gendered forms, which makes translating the word e.g. 'grateful' a little cumbersome - as I didn't want to assume the user's gender, I used both of the forms ('grateful' translates into 'wdzięczny/wdzięczna'). Maybe it doesn't look best, but it's the simplest solution.,
- I added an extra quote to the list; it's a hook from a popular Polish pop song. Translated into English, it says' Let's enjoy the little things, for in them is written the equation for happiness'. A little cliché, although also quite nicely worded (clearly not evident here ;) ). If it's not OK to have different sets of quotes for different languages, then I can delete it. Otherwise, I think the users could appreciate it.
- of course, I put my best effort into the translation, although I'm certain it could still benefit from someone else's inspection and correction

### CODE REVIEW

**Comment by alisonthemonster** [comment]
Thank you so much! To answer your questions/notes:

- channel_name, channel_description are both used in your phones settings so that you can control what types of notifications you get from an app. For example we could have reminder notifications and also in the future notifications that show you your older entries. A user would then be able to go to the settings and turn off the type of notifications they don't want to receive while still getting the ones they want. 
- reminder_title and notifs are used in the settings and in the actual notification itself
- error_parsing is when something went wrong when we try to import a file, either of your ideas works!
- I trust your judgement about the gendered forms, sounds good to me!
- The extra quote is awesome! 
- We can always come back and edit the translation, although I'm sure you did a fantastic job :)

**Comment by alisonthemonster** [comment]
Looks great to me! I just triggered the remaining tests and once those pass I'll merge the code 🎉

**Comment by kplich** [comment]
Unfortunately, this didn't cross my mind when I was translating the application, but I think that's not a minor concern: will the fonts used support Polish special characters (ą, ę, ł, ó, etc.)? I tried looking for a font used, but didn't manage to.

**Comment by alisonthemonster** [comment]
Don't worry I checked for that and everything looks good! You should see the release some time this week 😊

**Comment by kplich** [comment]
Great!
>
>

**Pull request merged**
